container_name: raster
raw_path: "floodscan/daily/v5/raw"
processed_path: "floodscan/daily/v5/processed"
sfed_historical:
  africa: "aer_sfed_area_300s_19980112_20231231_v05r01.nc"
  asia-australia: "aer_sfed_area_300s_19980112_20260331_v05r01_aa_no_ndt.nc"
  north-america: "aer_sfed_area_300s_19980112_20260331_v05r01_na_no_ndt.nc"
  south-america: "aer_sfed_area_300s_19980112_20260331_v05r01_sa_no_ndt.nc"
mfed_historical:
  africa: "aer_mfed_area_300s_19980112_20231231_v05r01.nc"
  asia-australia: "aer_mfed_area_300s_19980112_20260331_v05r01_aa_no_ndt.nc"
  north-america: "aer_mfed_area_300s_19980112_20260331_v05r01_na_no_ndt.nc"
  south-america: "aer_mfed_area_300s_19980112_20260331_v05r01_sa_no_ndt.nc"
coverage:
  start_date: 1998-01-12
  end_date: Null
  frequency: D
metadata:
  units: Flood fraction
  averaging_period: daily
  grid_resolution: 0.08333
  source: Atmospheric and Environmental Research (AER) FloodScan
  product: FloodScan
  version: 5
